### ISSUE TITLE
Support for Backstage static tokens

### ISSUE THREAD

**Issue by kunickiaj** [incident-io/catalog-importer#116]
Backstage no longer requires the jwt tokens for service to service auth and has moved to static tokens

https://backstage.io/docs/auth/service-to-service-auth#static-tokens

Support should be added for this -- its simply a bearer token that's passed in the authorization header without any extra code needed.

**Comment by isaacseymour** [comment]
Hi @kunickiaj! The Backstage source supports static tokens, you just need to add `sign_jwt: false` to your config (see [sources → Backstage](https://github.com/incident-io/catalog-importer/blob/master/docs/sources.md#backstage))

If that doesn't work for you please reopen this issue or drop us an email to support@incident.io 😄
