### ISSUE TITLE
Switch from CEL to Javascipt

### ISSUE THREAD

**Issue by lawrencejones** [incident-io/catalog-importer#61]
CEL is great but obscure, and most people won't have come across it before.

Javascript is ubiquitous and has several runtimes available to use in Go. I'd like us to switch to Javascript as the evaluation language, probably by supporting both through some tag (e.g. prefix any expression with `js:` or `cel:`) and eventually deprecating CEL for simplicity.

**Comment by lawrencejones** [comment]
Ticketed here: https://linear.app/incident-io/issue/RESP-1866/switch-from-cel-to-javascript-in-the-catalog-importer

**Comment by isaacseymour** [comment]
Closed by #78
