### ISSUE TITLE
Handle empty github repositories gracefully

### ISSUE THREAD

**Issue by rp-tucker** [incident-io/catalog-importer#68]
In trying to setup the catalog-importer to check an entire github org for catalog files, I hit an empty repository, which causes the catalog-importer to fail with this message:

```
catalog-importer: error: loading entries from source: github (repos=[obfuscated-org/*] files=[catalog/teams.jsonnet]): getting tree for 'obfuscated-org/obfuscated-repo' at ref main: GET https://api.github.com/repos/obfuscated-org/obfuscated-repo/git/trees/main?recursive=1: 409 Git Repository is empty. []
```

I would expect this to carry on happily in the same way it would if it hit a repo without catalog files.

**Comment by louisheath** [comment]
Hey @rp-tucker, thank you for raising this. I agree with your expectations of the code here and have made changes accordingly
