### ISSUE TITLE
Not possible to pass an API key for backstage source via command line

### ISSUE THREAD

**Issue by zetxek** [incident-io/catalog-importer#69]
Currently there doesn't seem to be a way to pass the API key for backstage to the command line:

https://github.com/incident-io/catalog-importer/blob/da1572d5abdc4f7b33b668da02f97596268a595f/cmd/catalog-importer/cmd/backstage.go#L21-L34

It's only possible to specify the API key for incident.io - assuming that backstage will not be authorized. That's not the case for hosted/production catalogs.

**Comment by kunickiaj** [comment]
It has to be passed via jsonnet in the token field, but command line would be a nice option

**Comment by louisheath** [comment]
Hey @zetxek, as @kunickiaj this is possible via the jsonnet configuration, but we have now updated the supported arguments to also enable this via the command line
